# Site settings
title: LYC4N.IO
email: canariasnorly@yahoo.com
description: "My dev blog and stuffs :]"
hello: "Hi! I'm <a href='/me' class='white'><b>Norly Canarias</b></a>, a Web Developer specializing Ruby on Rails and looking forward to explore Node.js and Python among other stuffs!"
pitch: "I'm currently working fulltime but would be interested in working on part time projects with you! 😉"
baseurl: ""
url: "https://lyc4n.github.io"

twitter:
  username: leecanarias

# defaults:
#   - scope:
#       path: ""
#     values:
#       image: "/assets/dubai-buildings.jpg"

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed
  sass_dir: _assets/stylesheets
collections:
  cheatsheets:
    output: true
    permalink: /cheatsheets/:path/
paginate: 15
paginate_path: "/page:num"
plugins:
  - jekyll-gist
  - jemoji
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-assets
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
gist:
  noscript: false
jekyll-archives:
  enabled: all
  enabled:
    - month
    - tags
  layouts:
    month: month-archive
    tag: tag-archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
assets:
  compress:
    css: sass
    js: uglifier
  assets:
    - '*.png'
    - '*.jpg'
    - '*.eot'
    - '*.svg'
    - '*.ttf'
    - '*.woff'
    - '*.woff2'
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
exclude:
  - Gemfile
  - Gemfile.lock
  - rakefile
  - .gitignore
port: 3000
